// Generated from content/blog/*.md by scripts/generate-blog-content.mjs.
// Do not edit this file directly.

import type { BlogPostSummary } from "./types";

export const blogPostSummaries: BlogPostSummary[] = [
  {
    "slug": "clear-creek-pear-brandy-en-US",
    "title": "Clear Creek Pear Brandy",
    "description": "How I encountered Clear Creek Pear Brandy and why I like it",
    "date": "2026-09-26",
    "author": "Eric",
    "language": "en-US",
    "translationKey": "clear-creek-pear-brandy",
    "spiritId": "brandy",
    "distilleryIds": [
      "clear-creek-brandy"
    ],
    "tags": [
      "labels",
      "brandy",
      "field notes"
    ]
  },
  {
    "slug": "clear-creek-pear-brandy-zh-TW",
    "title": "Clear Creek Pear Brandy (清溪白梨白蘭地)",
    "description": "我與白梨白蘭地的邂逅",
    "date": "2026-09-26",
    "author": "Eric",
    "language": "zh-TW",
    "translationKey": "clear-creek-pear-brandy",
    "spiritId": "brandy",
    "distilleryIds": [
      "clear-creek-brandy"
    ],
    "tags": [
      "labels",
      "brandy",
      "field notes"
    ]
  }
];
