// Generated from content/blog/*.md by scripts/generate-blog-content.mjs.
// Do not edit this file directly.

import type { BlogPost } from "./types";

export const blogPosts: BlogPost[] = [
  {
    "slug": "clear-creek-pear-brandy-en-US",
    "title": "Clear Creek Pear Brandy",
    "description": "How I encountered Clear Creek Pear Brandy and why I like it",
    "date": "2026-09-26",
    "author": "Eric",
    "language": "en-US",
    "translationKey": "clear-creek-pear-brandy",
    "spiritId": "brandy",
    "distilleryIds": [
      "clear-creek-brandy"
    ],
    "tags": [
      "labels",
      "brandy",
      "field notes"
    ],
    "body": ""
  },
  {
    "slug": "clear-creek-pear-brandy-zh-TW",
    "title": "Clear Creek Pear Brandy (清溪白梨白蘭地)",
    "description": "我與白梨白蘭地的邂逅",
    "date": "2026-09-26",
    "author": "Eric",
    "language": "zh-TW",
    "translationKey": "clear-creek-pear-brandy",
    "spiritId": "brandy",
    "distilleryIds": [
      "clear-creek-brandy"
    ],
    "tags": [
      "labels",
      "brandy",
      "field notes"
    ],
    "body": "# Clear Creek Pear Brandy (清溪白梨白蘭地)\n\nClear Creek（暫譯：清溪）品牌是位於美國奧勒岡州（Oregon）最古老與著名的釀酒廠之一。原本為Steve McCarthy先生於波特蘭（Portland）創立，現今的釀酒廠位於該州的西北部哥倫比亞河畔的胡德里弗（Hood River）。\n\n@[map](oregon 45.7089 -121.5123 \"Hood River, Oregon\")\n\nSteven McCarthy在奧勒岡當地也是一個傳奇人物。法律出身的Steve，在接手家族販售獵槍的工作之中，他開始愛上歐洲當地獨有的水果烈酒（Eau de vie）。美國太平洋西北部原本就是梨子與蘋果水果的主要產區，同時擁有梨子農場的Steve，他開始尋找是否可以在奧勒岡州釀白蘭地烈酒。"
  }
];
