export type ComparisonProfile = {
  ingredients: string;
  method: string;
  aging: string;
};

const profiles: Record<string, ComparisonProfile> = {
  "whisky:Scotch whisky": { ingredients: "Malted barley for malt whisky; other cereals may be used for grain whisky.", method: "Malt is pot distilled; grain whisky usually uses continuous columns. The two may be blended.", aging: "At least 3 years in Scotland in oak casks no larger than 700 L; used casks are common." },
  "whisky:Bourbon": { ingredients: "At least 51% corn, usually with rye or wheat plus malted barley.", method: "The cooked mash is fermented, then usually column distilled and doubled; maximum distillation strength is 80% ABV.", aging: "New charred oak is mandatory. No general minimum age; straight bourbon requires 2 years." },
  "whisky:Rye whiskey": { ingredients: "At least 51% rye in the US, commonly with corn and malted barley.", method: "A rye-heavy mash is fermented, then commonly column distilled and doubled within US strength limits.", aging: "New charred oak is mandatory. Straight rye requires at least 2 years." },
  "whisky:Tennessee whiskey": { ingredients: "Usually a corn-led mash meeting the federal composition rules for bourbon.", method: "Typically filtered through sugar-maple charcoal before barreling—the Lincoln County Process.", aging: "Aged in new charred oak in Tennessee; state rules and limited exceptions apply." },
  "whisky:Irish whiskey": { ingredients: "Malted barley, unmalted barley and other cereals, depending on the named category.", method: "Pot or column distilled; triple distillation is common but not universal. Pot-still recipes may combine malted and unmalted barley.", aging: "At least 3 years in wooden casks on the island of Ireland." },
  "whisky:Canadian whisky": { ingredients: "Corn and wheat often form a light base; rye or other grains supply flavoring whisky.", method: "Grains may be fermented, distilled and matured separately, then blended; columns and pot stills both play a role.", aging: "At least 3 years in small wood in Canada." },
  "whisky:Japanese whisky": { ingredients: "Malted barley and other cereal grains, depending on malt, grain or blended style.", method: "Pot stills for malt and columns for grain; producers often make many internal distillate styles for blending.", aging: "The industry standard requires at least 3 years in Japan in wooden casks no larger than 700 L." },
  "whisky:Taiwanese single malt whisky": { ingredients: "Malted barley, water and yeast at one Taiwanese distillery.", method: "Pot-distilled malt whisky shaped by warm-climate fermentation and maturation choices.", aging: "Taiwan's heat accelerates extraction and evaporation; cask activity can become prominent at relatively young ages." },
  "whisky:Indian single malt whisky": { ingredients: "Malted barley—often Indian-grown—fermented and distilled at one Indian distillery.", method: "Pot distillation preserves malt and fruit character; producer climate and still choices vary.", aging: "Hot maturation can concentrate fruit, spice and oak quickly, with high evaporation losses." },

  "brandy:Cognac": { ingredients: "Dry, high-acid white wine, principally from Ugni Blanc grapes.", method: "Distilled twice in copper Charentais pot stills during the legally defined season.", aging: "Aged in French oak in the region; VS, VSOP and XO refer to the youngest spirit in the blend." },
  "brandy:Armagnac": { ingredients: "High-acid wine from permitted grapes, often Ugni Blanc, Baco, Folle Blanche or Colombard.", method: "Commonly distilled once in a small continuous Armagnac still; pot distillation is also permitted.", aging: "Gascon oak is traditional; vintage and age-stated bottlings sit alongside blends." },
  "brandy:Brandy de Jerez": { ingredients: "Wine distillates, historically tied to Airén and other Spanish white grapes.", method: "Characterful holandas and lighter distillates may be combined to balance fruit and finesse.", aging: "Aged in the Jerez area, typically by solera, in casks previously seasoned with Sherry." },
  "brandy:Pisco": { ingredients: "Permitted aromatic or non-aromatic grapes; the lists differ in Peru and Chile.", method: "Grape must is fermented and batch distilled; Peruvian pisco is distilled to bottling strength without dilution.", aging: "Peru requires inert-vessel resting; Chile permits wood-aged categories." },
  "brandy:Grappa": { ingredients: "Fresh grape pomace—the skins, seeds and remaining pulp after winemaking.", method: "Steam, batch or continuous systems capture volatile aromas from this solid raw material.", aging: "Often clear and unaged, though wood-rested and aged styles are established." },
  "brandy:Calvados": { ingredients: "Cider apples and, where permitted, pears from defined Normandy orchards.", method: "Fruit is fermented to cider or perry, then column or double-pot distilled depending on appellation.", aging: "Oak maturation is required; minimums vary by appellation and age claim." },
  "brandy:Fruit eaux-de-vie": { ingredients: "Fermented pear, cherry, plum, raspberry or another named fruit.", method: "Usually batch distilled to retain vivid varietal fruit rather than neutralize it.", aging: "Normally rested in inert vessels and bottled clear; oak is uncommon." },
  "brandy:Singani": { ingredients: "Moscatel of Alexandria grapes grown in Bolivia's authorized high valleys.", method: "Fresh-grape wine is distilled to preserve intense floral and citrus aroma.", aging: "Generally rested in inert vessels and bottled clear rather than oak-aged." },
  "brandy:South African pot-still brandy": { ingredients: "Wine—often from Chenin Blanc or Colombard—distilled entirely in copper pot stills.", method: "Double pot distillation creates a full-flavored wine spirit under South African rules.", aging: "At least 3 years in oak, adding vanilla, dried fruit and baking spice." },

  "rum:Molasses-based rum": { ingredients: "Molasses diluted with water—the concentrated by-product of sugar refining.", method: "Fermentation can be brief and clean or long and bacteria-rich; pot, column and blended distillates all occur.", aging: "May be unaged or oak-aged in tropical or continental climates; rules vary by origin." },
  "rum:Cane-juice rum": { ingredients: "Fresh-pressed sugar-cane juice, processed quickly before it spoils.", method: "Juice is fermented soon after harvest, then pot or column distilled depending on local tradition.", aging: "Often bottled white after resting, but oak-aged versions are also common." },
  "rum:Rhum agricole": { ingredients: "Fresh cane juice; Martinique AOC adds defined cane and harvest rules.", method: "Fresh juice is fermented and characteristically distilled on Creole columns for aromatic cane character.", aging: "Blanc is rested; élevé sous bois and vieux terms signal increasing wood maturation." },
  "rum:Jamaican rum": { ingredients: "Usually molasses, water and fermentation material such as dunder or muck where used.", method: "Often long, complex fermentation builds esters; double-retort pot stills are iconic, alongside columns and blends.", aging: "White, lightly aged and long tropical-aged forms exist; the GI governs authentic origin." },
  "rum:Cuban-style rum": { ingredients: "Molasses, generally fermented for a relatively light, clean base.", method: "Light column spirit is blended with more characterful aguardiente and often charcoal-filtered.", aging: "Typically oak-aged in stages, blended and filtered; the style phrase itself sets no universal rule." },
  "rum:Cachaça": { ingredients: "Fresh sugar-cane juice from Brazil.", method: "Juice is fermented, then pot or column distilled within Brazil's prescribed strength range.", aging: "Often unaged; oak and native woods such as amburana can be used for resting or aging." },
  "rum:Clairin": { ingredients: "Haitian cane juice or cane syrup, often from locally named cane varieties.", method: "Long local fermentations and small stills preserve intense cane and microbial character.", aging: "Traditionally bottled unaged, though rested and cask-aged experiments exist." },

  "agave:Tequila": { ingredients: "Blue Weber agave from authorized territory; mixto may include permitted non-agave sugars.", method: "Mature hearts are cooked, crushed, fermented and usually twice distilled; ovens, autoclaves and diffusers produce different results.", aging: "Blanco is unaged or briefly rested; reposado, añejo and extra añejo mark longer oak aging." },
  "agave:Mezcal": { ingredients: "One or more permitted agave species grown in certified municipalities.", method: "Often earth-roasted, crushed, open-fermented and batch distilled in copper, clay or other permitted stills.", aging: "Joven is unaged; reposado, añejo and glass-matured expressions also exist." },
  "agave:Ancestral mezcal": { ingredients: "Permitted agave species harvested inside the Mezcal denomination.", method: "Pit cooking, manual or animal crushing, natural-material fermentation and direct-fire clay or wood stills define the regulated ancestral class.", aging: "Most is bottled joven so agave, clay, smoke and fermentation remain visible; other maturation classes may occur." },
  "agave:Bacanora": { ingredients: "Commonly Agave angustifolia from the protected Sonoran territory.", method: "Roasted hearts are milled, fermented and usually batch distilled in compact regional stills.", aging: "Frequently bottled young, with rested and oak-aged examples available." },
  "agave:Raicilla": { ingredients: "Permitted agaves from protected municipalities in Jalisco and Nayarit.", method: "Coastal and mountain traditions differ in roasting, milling, fermentation vessels and small still designs.", aging: "Usually joven and unaged, though wood-aged expressions are permitted." },
  "agave:Sotol": { ingredients: "Dasylirion (desert spoon), not agave, from northern Mexican protected territory.", method: "Plant hearts are roasted, crushed, fermented and typically twice batch distilled.", aging: "Most is bottled young; reposado and añejo styles add oak influence." },

  "gin:London Dry Gin": { ingredients: "Neutral agricultural spirit with juniper and botanicals such as citrus and coriander.", method: "Flavor must be created in redistillation; only tightly limited additions are allowed afterward.", aging: "Normally unaged. “Dry” describes production and sweetness limits, not time in wood." },
  "gin:Distilled gin": { ingredients: "Agricultural spirit redistilled with juniper and other natural botanicals.", method: "Maceration, vapor infusion or multiple distillates build the recipe; more post-distillation flavoring may be allowed than in London Dry.", aging: "Usually unaged, with occasional rested or barrel-aged interpretations." },
  "gin:Contemporary gin": { ingredients: "Neutral spirit, juniper and a recipe led by citrus, floral, tea, fruit or savory botanicals.", method: "Extraction follows the producer; the recipe's emphasis, not a distinct legal process, defines the market style.", aging: "Typically unaged and designed for fresh botanical clarity." },
  "gin:Old Tom gin": { ingredients: "A juniper spirit that may use neutral spirit or a maltier base, often with some sweetening.", method: "Botanicals are distilled or infused; no single global Old Tom recipe exists.", aging: "Can be clear and unaged or briefly cask-aged; sweetness and wood are producer choices." },
  "gin:Genever": { ingredients: "Malt wine from grains, combined with juniper-flavored distillate or spirit.", method: "Fermented grain supplies cereal weight; pot-distilled malt wine and botanical components are composed under protected rules.", aging: "Jonge and oude refer chiefly to recipe, not age; wood-aged versions also exist." },
  "gin:Barrel-aged gin": { ingredients: "Gin built from juniper, botanicals and an agricultural spirit base.", method: "A finished gin or botanical distillate is placed in wood; cask type and previous use determine the result.", aging: "No universal minimum: brief resting preserves botanicals, while longer aging adds toast, vanilla, tannin and spice." },

  "vodka:Neutral vodka": { ingredients: "Highly rectified agricultural spirit, often from wheat, corn, rye or potato, plus water.", method: "High-strength continuous rectification removes most congeners, followed by filtration and proofing.", aging: "Unaged; filtration, resting and proofing water shape final texture." },
  "vodka:Characterful vodka": { ingredients: "Named grain, potato, grape or another fermentable agricultural raw material.", method: "Fermentation, rectification and lighter filtration aim to retain subtle source character and texture.", aging: "Usually unaged, sometimes rested before dilution and bottling." },
  "vodka:Flavored vodka": { ingredients: "Vodka plus declared fruit, spice, herb or other flavoring; sweetening may be present.", method: "The base is rectified first; extract, essence, maceration or a combination adds flavor afterward.", aging: "Normally unaged and bottled once flavor, sweetness and proof are balanced." },
  "vodka:Infused vodka": { ingredients: "Vodka steeped with whole or cut fruit, herbs, tea, spice or other ingredients.", method: "Maceration extracts aroma and often color; the infusion is usually not redistilled.", aging: "Short marrying or resting rather than oak aging; freshness is usually the goal." },
  "vodka:Potato vodka": { ingredients: "Potatoes converted from starch to fermentable sugar, then fermented with yeast.", method: "Repeated or continuous rectification creates vodka while production choices may preserve creamy, earthy texture.", aging: "Unaged; filtration, resting water and final proof are more important than wood." },

  "asian:Strong-aroma baijiu": { ingredients: "Sorghum alone or mixed grains, saccharified with large-brick daqu.", method: "Solid-state mud-pit fermentation through repeated cycles, followed by steam distillation and blending.", aging: "Commonly aged in inert pottery or ceramic, not flavoring oak." },
  "asian:Sauce-aroma baijiu": { ingredients: "Sorghum and high-temperature wheat daqu.", method: "Repeated high-temperature cooking, fermentation and steam-distillation rounds over a long cycle.", aging: "Extended ceramic or other inert-vessel aging precedes intricate blending." },
  "asian:Light-aroma baijiu": { ingredients: "Usually sorghum with low-temperature daqu.", method: "Relatively short, clean solid-state fermentation—traditionally in stone jars—then steam distillation.", aging: "Rested in inert vessels before blending; wood flavor is not the objective." },
  "asian:Rice-aroma baijiu": { ingredients: "Rice with a small-qu culture.", method: "Semi-solid or liquid fermentation creates a soft profile before batch distillation.", aging: "Usually rested in non-oak vessels before blending and bottling." },
  "asian:Honkaku shōchū": { ingredients: "A permitted main ingredient—often sweet potato, barley, rice or buckwheat—plus kōji.", method: "Kōji drives two-stage fermentation; a single distillation preserves raw-material character.", aging: "Rested in tank, clay or sometimes wood; prolonged aging is optional." },
  "asian:Awamori": { ingredients: "Traditionally long-grain indica rice inoculated throughout with black kōji.", method: "All-kōji rice undergoes one fermentation and one batch distillation.", aging: "May be bottled young or aged as kusu, traditionally in earthenware vessels." },
  "asian:Diluted soju": { ingredients: "Highly rectified agricultural spirit, water and sometimes sweetening or flavor adjustments.", method: "Continuously distilled neutral spirit is diluted, blended and filtered to approachable strength.", aging: "Unaged and generally bottled soon after blending." },
  "asian:Distilled soju": { ingredients: "Rice or other grains, traditionally converted with nuruk culture.", method: "A characterful grain mash is fermented and usually batch distilled.", aging: "May be rested or aged in pottery or wood, depending on producer and regional style." },
  "asian:Kaoliang": { ingredients: "Sorghum with a grain-based starter culture, commonly including wheat.", method: "Solid-state fermentation and batch distillation preserve powerful sorghum and fermented-fruit aroma.", aging: "Rested in ceramic or other inert vessels before blending; Kinmen and Matsu traditions differ." },

  "flavoured:Liqueurs": { ingredients: "A spirit base, sugar and flavors from fruit, nuts, herbs, cream, coffee or spice.", method: "Flavor is redistilled, macerated or directly extracted, then blended and sweetened to the applicable threshold.", aging: "Usually married in tank; some recipes or bases receive cask aging." },
  "flavoured:Amari": { ingredients: "Spirit or wine-derived base with bitter roots, bark, herbs, citrus and sugar.", method: "Botanicals are macerated or separately extracted, then blended to balance bitterness and sweetness.", aging: "Tank resting is common; some amari develop in cask." },
  "flavoured:Aniseed spirits": { ingredients: "Agricultural spirit flavored chiefly with anise, star anise or fennel-like botanicals.", method: "Anise oils are extracted by maceration, distillation or blending under the named category's rules.", aging: "Generally clear and unaged; water causes the characteristic louche in many styles." },
  "flavoured:Aquavit": { ingredients: "Agricultural spirit flavored primarily with caraway and/or dill, often with citrus and spice.", method: "Botanicals are macerated or redistilled into a clean base; protected origins may add rules.", aging: "Can be clear and unaged or cask-aged, sometimes through maritime travel traditions." },
  "flavoured:Cocktail bitters": { ingredients: "High-proof spirit extracting concentrated bitter roots, bark, spice and aromatic botanicals.", method: "Long maceration, percolation and blending create a formula intended for drops or dashes.", aging: "Rested to marry; occasional barrel aging, but concentration matters more than age." },
  "flavoured:Flavored vodka": { ingredients: "Vodka plus fruit, spice, herb or confectionery flavoring, sometimes with sugar.", method: "Essence, extract, maceration or direct blending adds the declared flavor to the finished vodka base.", aging: "Normally unaged, then rested briefly for flavor integration." },
  "flavoured:Infused vodka": { ingredients: "Vodka steeped with fruit, herbs, tea, spice or another named ingredient.", method: "Maceration extracts aroma and often natural color; the result is generally filtered without redistilling away that character.", aging: "Usually married briefly in tank rather than oak-aged, with freshness and ingredient clarity as the goal." },
  "flavoured:Absinthe": { ingredients: "A spirit base flavored chiefly with wormwood, anise and fennel, often with supporting herbs.", method: "Botanicals are macerated and commonly redistilled; a secondary herbal coloring step may create a verte style.", aging: "Usually rested to marry rather than oak-aged; dilution releases oils and creates the louche." },
};

export function getComparisonProfile(categoryId: string, subtypeName: string) {
  return profiles[`${categoryId}:${subtypeName}`];
}
